const Courses = [
  {
    id: "1",
    title: "UI/UX Design",
    cover: require("./UI-UX.png"),
    price: "$254.36",
    category: "Web Design",
    bestSeller: true,
  },
  {
    id: "2",
    title: "CSS",
    cover: require("./CSS.png"),
    price: "$254.36",
    category: "Web Design",
    bestSeller: true,
  },
  {
    id: "3",
    title: "Digital Marketing",
    cover: require("./Digital Marketing.png"),
    price: "$254.36",
    category: "Marketing",
    bestSeller: true,
  },
  {
    id: "4",
    title: "UI/UX Design",
    cover: require("./UI-UX-2.png"),
    price: "$254.36",
    category: "Web Design",
    bestSeller: true,
  },
  {
    id: "5",
    title: "UI/UX Design",
    cover: require("./UI-UX.png"),
    price: "$254.36",
    category: "Web Design",
    bestSeller: true,
  },
  {
    id: "6",
    title: "Digital Marketing",
    cover: require("./Digital Marketing.png"),
    price: "$254.36",
    category: "Marketing",
    bestSeller: true,
  },
  {
    id: "7",
    title: "UI/UX Design",
    cover: require("./UI-UX.png"),
    price: "$254.36",
    category: "Web Design",
    bestSeller: true,
  },
  {
    id: "8",
    title: "CSS",
    cover: require("./CSS.png"),
    price: "$254.36",
    category: "Web Design",
    bestSeller: true,
  },
  {
    id: "9",
    title: "Digital Marketing",
    cover: require("./Digital Marketing.png"),
    price: "$254.36",
    category: "Marketing",
    bestSeller: true,
  },
  {
    id: "10",
    title: "UI/UX Design",
    cover: require("./UI-UX-2.png"),
    price: "$254.36",
    category: "Web Design",
    bestSeller: true,
  },
  {
    id: "11",
    title: "UI/UX Design",
    cover: require("./UI-UX.png"),
    price: "$254.36",
    category: "Web Design",
    bestSeller: true,
  },
  {
    id: "12",
    title: "Digital Marketing",
    cover: require("./Digital Marketing.png"),
    price: "$254.36",
    category: "Marketing",
    bestSeller: true,
  },
  {
    id: "13",
    title: "UI/UX Design",
    cover: require("./UI-UX.png"),
    price: "$254.36",
    category: "Web Design",
    bestSeller: true,
  },
  {
    id: "14",
    title: "CSS",
    cover: require("./CSS.png"),
    price: "$254.36",
    category: "Web Design",
    bestSeller: true,
  },
  {
    id: "15",
    title: "Digital Marketing",
    cover: require("./Digital Marketing.png"),
    price: "$254.36",
    category: "Marketing",
    bestSeller: true,
  },
  {
    id: "16",
    title: "UI/UX Design",
    cover: require("./UI-UX-2.png"),
    price: "$254.36",
    category: "Web Design",
    bestSeller: true,
  },
  {
    id: "17",
    title: "UI/UX Design",
    cover: require("./UI-UX.png"),
    price: "$254.36",
    category: "Web Design",
    bestSeller: true,
  },
  {
    id: "18",
    title: "Digital Marketing",
    cover: require("./Digital Marketing.png"),
    price: "$254.36",
    category: "Marketing",
    bestSeller: true,
  },
];

export default Courses;
